title: Scripture Examined
description: Dedicated to the study of the Pauline Epistles.

baseurl: ""
url: "https://god.stannellc.com"

markdown: kramdown

exclude: [Node_modules, vendor]

# rebuild test
