title: Scripture Examined
description: Dedicated to the study of the Pauline Epistles.

baseurl: ""
url: "https://god.stannellc.com"

markdown: kramdown
incremental: true
exclude: [Node_modules, vendor]
